apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin 
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin-helm
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/jellyfin/jellyfin
      tag: latest
      pullPolicy: IfNotPresent
    jellyfin:
      env:
        - name: TZ
          value: Europe/Berlin
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: jellyfin.homelab.fritz.box
          paths:
            - path: /
              pathType: Prefix
        - host: jellyfin.homelab.local
          paths:
            - path: /
              pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: "jellyfin-config-pvc"
      media:
        enabled: true
        existingClaim: "media-nfs-pvc"
