apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin 
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.2.1"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            securityContext:
              privileged: true # HW acceleration
            persistence:
              dri:
                enabled: true
                type: hostPath
                hostPath: /dev/dri
                globalMounts:
                  - path: /dev/dri
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: latest
            env:
              # Timezone is important for air dates
              TZ: Europe/Berlin 
    service:
      main:
        ports:
          http:
            port: 8096 
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: jellyfin.local
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        enabled: true
        # Use a PVC here if you want to save Sonarr settings
        # type: persistentVolumeClaim
        # accessMode: ReadWriteOnce
        # size: 1Gi
        type: emptyDir 
      media:
        enabled: true
        existingClaim: media-nfs-pvc
        globalMounts:
          - path: /media
