[server]
bind_addr = "0.0.0.0:2333"
default_token = "${RATHOLE_TOKEN}"

[server.services.http]
bind_addr = "0.0.0.0:8080"

[server.services.https]
bind_addr = "0.0.0.0:8443"

[server.services.fritzbox-wg]
bind_addr = "0.0.0.0:51820"
type = "udp"
