apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
