apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: coredns
data:
  Corefile: |
    .:53 {
        errors
        log

        # 1. Match both the apex domain AND all subdomains
        rewrite stop name regex .*\.?homelab\.fritz\.box traefik-ingress.local
        rewrite stop name regex .*\.?homelab\.local traefik-ingress.local

        # 2. Resolve them to your Traefik IP
        hosts {
            192.168.1.80 traefik-ingress.local
            fallthrough
        }

        # 3. Forward unknown queries to the Fritz!Box first, THEN Google
        # This keeps your standard router DNS functions alive!
        forward . 192.168.1.1 8.8.8.8 {
            max_concurrent 1000
        }
    }
