apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
spec:
  capacity:
    storage: 3Ti # Just a placeholder limit
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.41
    path: /volume2/Gemeinsame_Dateien
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # Empty string required for static binding
  volumeName: media-nfs-pv
  resources:
    requests:
      storage: 3Ti
